stages:
  - test

variables:
  GIT_DEPTH: 3

lint:
  stage: test
  image: cljkondo/clj-kondo:2022.06.22-alpine
  cache: {}
  when: always
  script:
  - clj-kondo --lint src test --config '{:output {:exclude-files ["java"]}}'

unit-test:
  stage: test
  when: always
  image: clojure:temurin-17-tools-deps-alpine
  script:
    - clojure -M:test
